behaviors:
  MoveToGoal:
    trainer_type: ppo
    hyperparameters:
      batch_size: 10
      buffer_size: 100
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 700000
    time_horizon: 64
    summary_freq: 10000

environment_parameters:
  # This is where you define the environment parameters related to curriculum
  wall_height:  # Name of the environment parameter you're modifying (could be anything)
    curriculum:
      - name: Increase Wall Height Slowly
        completion_criteria:
          measure: progress  # The measure to track agent's progress (could be reward, steps, etc.)
          behavior: MoveToGoal  # Link to the specific behavior of your agent
          signal_smoothing: true  # Optional: smooth the reward signal
          min_lesson_length: 100  # Minimum steps before progressing to next lesson
          threshold: 0.2  # Progress threshold to move to next curriculum stage
        value: 1.0  # Start value for wall_height

      - name: Raise Wall Height
        completion_criteria:
          measure: progress
          behavior: MoveToGoal
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.6  # Threshold for when to advance to the next lesson
          require_reset: true  # Reset environment at the start of the new lesson
        value:
          sampler_type: uniform  # Randomly sample between values within a range
          sampler_parameters:
            min_value: 3.0
            max_value: 7.0  # Range of values for wall height during this lesson

      - name: Final Wall Height
        value: 8.0  # Final wall height after the curriculum ends
