behaviors:
  MoveToGoal:
    trainer_type: ppo
    hyperparameters:
      batch_size: 10
      buffer_size: 100
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 700000
    time_horizon: 64
    summary_freq: 10000

environment_parameters:
  wall_height:
    curriculum:
      - name: No Wall
        completion_criteria:
          measure: reward  
          behavior: MoveToGoal
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.8  
        value: 0.0  

      - name: Introduce Easy Wall 
        completion_criteria:
          measure: reward
          behavior: MoveToGoal
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.8  
          require_reset: true
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 1.0
            max_value: 2.0


      - name: Medium Wall 
        completion_criteria:
          measure: reward
          behavior: MoveToGoal
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.8  
          require_reset: true
        value:
         sampler_type: uniform
         sampler_parameters:
           min_value: 3.0
           max_value: 4.0

      - name: Final Wall Height
        value: 5.25  

